### ISSUE TITLE
CMake version management and requirements

### ISSUE THREAD

**Issue by albestro** [eth-cscs/cmake-recipes#5]
In this repository, we are going to provide CMake stuff that, obviously, makes use of CMake functionalities.

CMake adds new functionalities, but also change existing ones, in the form and/or in the behavior.

I think it is unreasonable to address all CMake versions and we may address at most just newer ones, where "modern CMake" started (3.12?). But, even just in the last versions, there are differences.

The big questions are:
- **What are the requirements that we want to impose to use this repository?**
- **How do we want to manage this requirements, now and in the future?**

**Comment by havogt** [comment]
I propose we do it on a per file basis. Each file should come with a header that explains how to use it and specifies the requirement. If we fix a specific version for the whole repository we would have to regularly update this requirement as new features become available.

**Comment by lukasm91** [comment]
Each file can call `cmake_minimum_required(VERSION X.Y)`. As these files are included with `include`, they get a new policy scope anyway, so they should not interfere with the caller.
